[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "snowflake-cli-labs"
dynamic = ["version"]
requires-python = ">=3.8"
description = "Snowflake CLI"
dependencies = [
  "snowflake-connector-python",
  "requirements-parser",
  "toml",
  "pluggy~=1.0",
  "pyyaml",
  "typer",
  "rich"
]

[project.urls]
"Source code" = "https://github.com/Snowflake-Labs/snowcli"

[project.scripts]
snow = "snowcli._cli:APP"

[tool.hatch.version]
path = "src/snowcli/__about__.py"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
]

[tool.hatch.build.targets.wheel]
packages = ["src/snowcli", "src/templates"]
